@0xdbb9ad1f14bf0b36;  # unique file ID, generated by `capnp id`

interface PHoneIF {
    testMessage @0 (a: Person) -> (result: Int8);
}

struct Person {
  name @0 :Text;
  birthdate @3 :Date(DymmyB);

  email @1 :Text;
  phones @2 :List(PhoneNumber);

  struct PhoneNumber {
    number @0 :Text;
    type @1 :Type;

    enum Type {
      mobile @0;
      home @1;
      work @2;
    }
  }
}

struct Dymmy {
  year @0 :UInt16;
}

struct DymmyB {
  aa @0 : Int8;
}

struct Date (YEARTYPE) {
  year @0 :YEARTYPE;
  month @1 :UInt8;
  day @2 :UInt8;
  struct DymmyA {
    year @0 :Date(Dymmy);
    test @1 : YEARTYPE;
  }
  test @3 :DymmyA;
}